# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "fastlanetestapp")
  end

  desc "Test application"
  lane :test do
    run_tests(scheme: "fastlanetestapp")
  end

  desc "Initialize app on developer portal"
  lane :developer_portal_init do
    produce(
      skip_itc: true,
      app_name: "FastlaneTestApp"
    )
  end

  desc "Generate development certificate"
  lane :generate_development_provisioning_profile do
    sync_code_signing(
      type: "development"
    )
  end

  desc "Sync development certificate (readonly)"
  lane :sync_development_provisioning_profile do
    sync_code_signing(
      type: "development",
      readonly: true
    )
  end

  desc "Build development version of app"
  lane :build_development do
    sync_code_signing(type: "development", readonly: true)
    build_ios_app(
      clean: true,
      output_directory: "output",
      silent: true,
      include_symbols: true,
      export_method: "development"
    )
  end
end
